version: '3.9'

services:
  backend:
    depends_on:
      - database
    build: ./backend
    volumes:
      - ./backend:/app
    container_name: blitz-backend
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=blitz
      - HOST=database
      - JWT_SECRET=5zV&@8}znYJ/VkZ9
    tty: true
    stdin_open: true
  database:
    image: mysql:8.0.21
    container_name: blitz-database
    restart: unless-stopped
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=blitz
