version: '3.9'

services:
  backend:
    depends_on:
      database:
        condition: service_healthy
    build: ./backend
    volumes:
      - ./backend:/app
    container_name: blitz-backend
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=blitz
      - HOST=database
      - JWT_SECRET=5zV&@8}znYJ/VkZ9
    tty: true
    stdin_open: true
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001'] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
  database:
    image: mysql:8.0.21
    container_name: blitz-database
    restart: unless-stopped
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=blitz
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost'] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
